### ISSUE TITLE
SHA256 hash seems to be invalid

### ISSUE THREAD

**Issue by cepxeo** [eid3t1c/Hash_Extender#1]
Hello, I am trying to use the tool for hash extension. 
Let's say my secret key is "key", the known message is "message".

The SHA256 of "keymessage" is 8ebbc3081b0700d1c226cafda9032a6a11224ed7367c5d59425e548ac4e70c0e

Now I want to extend it with the word "extend"
SHA256 of "keymessageextend" is 34da7d5df4ee5f042ebf19846e3b43325fda82d8c0381818fdc93ac0fdaafddd

Then I run: python Length_Extender.py -f SHA256 -s 8ebbc3081b0700d1c226cafda9032a6a11224ed7367c5d59425e548ac4e70c0e -d message -e extend -k 
3

The tool output is "New Signature  8fd6775dc06d90221591613ec9329de7430f13b62d93d53c6e9885a53e62bbbd"

Doesn't took like a match with "keymessageextend" hash. What I'm doing wrong here?

**Comment by eid3t1c** [comment]
It seems like you haven't included the padding. The "keymessage" before getting hashed it was padded to a block of 64 bytes or 512 bits. Hence, the  hash 8ebbc3081b0700d1c226cafda9032a6a11224ed7367c5d59425e548ac4e70c0e  was produced from the 
b"keymessage" + b"\x80" + b"\x00" * (64 -8 - 1 -10) + (10*8).to_bytes(8,byteorder="big"). Now, since you want to get a valid hash with the word "extend" all you have to do is include the padding before hashing it like this : 

'keymessage\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Pextend'

the first 64 bytes will be hashed creating the hash you already know and will be registered as the new state of sha256 to hash the message "extend" + padding of sha256 resulting to :

8fd6775dc06d90221591613ec9329de7430f13b62d93d53c6e9885a53e62bbbd

If you have any more questions you can add me on discord "eid3t1c"

**Comment by cepxeo** [comment]
Understood, many thanks for explanation!
